war instead of jar

diff --git a/sti/bin/assemble b/sti/bin/assemble
--- a/sti/bin/assemble
+++ b/sti/bin/assemble
@@ -67,7 +67,7 @@ if [ -f "$LOCAL_SOURCE_DIR/pom.xml" ]; then
   # Copy built artifacts (if any!) from the target/ directory
   # (or $ARTIFACT_DIR if specified)
   # to the $DEPLOY_DIR directory for later deployment
-  copy_artifacts "$ARTIFACT_DIR" jar
+  copy_artifacts "$ARTIFACT_DIR" war
 
   # optionally clear the local maven repository after the build
   clear_maven_repository
@@ -111,7 +111,7 @@ elif [ -f "$LOCAL_SOURCE_DIR/build.gradle" ]; then
   # Copy built artifacts (if any!) from the target/ directory
   # (or $ARTIFACT_DIR if specified)
   # to the $DEPLOY_DIR directory for later deployment
-  copy_artifacts "$ARTIFACT_DIR" jar
+  copy_artifacts "$ARTIFACT_DIR" war
 
 
   # clean up after maven
@@ -127,19 +127,19 @@ else
   # artifacts (*.war, *.jar)
   ARTIFACT_DIR=${ARTIFACT_DIR:-.}
 
-  copy_artifacts "$ARTIFACT_DIR" jar
+  copy_artifacts "$ARTIFACT_DIR" war
 fi
 
 # As Microservices you should only have 1 fat jar
 # if compgen -G "/tmp/src/*" >/dev/null; then
 # TODO: Review how best move these
-if [ $(ls ${DEPLOY_DIR}/*${APP_SUFFIX}.jar | wc -l) -eq 1 ]; then
-  echo "[INFO] Copying ${DEPLOY_DIR}/*${APP_SUFFIX}.jar into ${DEPLOY_DIR}/app.jar"
-  cp ${DEPLOY_DIR}/*${APP_SUFFIX}.jar ${DEPLOY_DIR}/app.jar
-  [ ! -f ${DEPLOY_DIR}/app.jar ] && echo "Application could not be properly built." && exit 1
-  echo "[INFO] Application jar file is located in ${DEPLOY_DIR}/app.jar"
+if [ $(ls ${DEPLOY_DIR}/*${APP_SUFFIX}.war | wc -l) -eq 1 ]; then
+  echo "[INFO] Copying ${DEPLOY_DIR}/*${APP_SUFFIX}.war into ${DEPLOY_DIR}/app.war"
+  cp ${DEPLOY_DIR}/*${APP_SUFFIX}.war ${DEPLOY_DIR}/app.war
+  [ ! -f ${DEPLOY_DIR}/app.war ] && echo "Application could not be properly built." && exit 1
+  echo "[INFO] Application war file is located in ${DEPLOY_DIR}/app.war"
 else
-  echo "[ERROR] No app.jar file located in ${DEPLOY_DIR}"
+  echo "[ERROR] No app.war file located in ${DEPLOY_DIR}"
   exit 1
 fi
 
